artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: null
  local_data_file: artifacts/data_ingestion/data_kidney.zip
  unzip_dir: artifacts/data_ingestion


prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5
  params_classes: 4     # ðŸ”¥ IMPORTANT â†’ number of kidney classes

prepare_callbacks:
  root_dir: artifacts/prepare_callbacks
  tensorboard_root_log_dir: artifacts/prepare_callbacks/tensorboard
  checkpoint_model_filepath: artifacts/prepare_callbacks/checkpoints/model.h5


training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5
  training_data: artifacts/data_ingestion/data_kidney